### ISSUE TITLE
What outliers stands for?

### ISSUE THREAD

**Issue by youjiaSHTU** [hoshino042/NormalIntegration#1]

**Comment by xucao-42** [comment]
The outliers stand for jittered normal vectors at random pixels in a normal map.
In my python script, we can randomly choose pixels (e.g., 1% of all pixels) and jitter the normal vectors at those pixels.

**Comment by youjiaSHTU** [comment]
> The outliers stand for jittered normal vectors at random pixels in a normal map. In my python script, we can randomly choose pixels (e.g., 1% of all pixels) and jitter the normal vectors at those pixels.

Thanks a lot!
